apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: novacorp-ingress
  namespace: novacorp
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-west-2:716769866080:certificate/7facdf5c-9760-4088-9bcc-95097167df5b
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/subnets: subnet-0009ea10e246ef04a,subnet-0862e466a9328717f
spec:
  rules:
    - host: novacorp.titotest.co.uk
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: novacorp-api
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: novacorp-frontend
                port:
                  number: 80