apiVersion: apps/v1
kind: Deployment
metadata:
  name: novacorp-frontend
  namespace: novacorp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: novacorp-frontend
  template:
    metadata:
      labels:
        app: novacorp-frontend
    spec:
      containers:
        - name: frontend
          image: 716769866080.dkr.ecr.eu-west-2.amazonaws.com/novacorp/frontend:02cd2f3f27bca099cb54cfbf0b8f456f0823c9e4
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi