apiVersion: v1
kind: ServiceAccount
metadata:
  name: novacorp-api
  namespace: novacorp
  annotations:
    eks.amazonaws.com/role-arn:  eks.amazonaws.com/role-arn: arn:aws:iam::716769866080:role/cop-novacorp-api-role